name: cashtree_hot_deal
description: A new Flutter project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4

  # State Management
  get: ^4.6.1

  # Reactive 
  reactive_forms: ^11.0.1

  # Handle internationalized/localized message 
  # intl: ^0.17.0
  intl_utils: ^2.6.1

  # Pick image from library or taking image
  image_picker: ^0.8.4+10  

  google_fonts: ^2.3.1

  dio: ^4.0.4

  equatable: ^2.0.3

  flutter_secure_storage: ^5.0.2

  mockito: ^5.2.0

  http_mock_adapter: ^0.3.1

  # Firebase
  # firebase_core: ^1.13.1
  # firebase_analytics: ^9.1.2
  # firebase_messaging: ^11.2.8
  # firebase_crashlytics: ^2.5.3
  # firebase_performance: ^0.8.0+7

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
